#!/usr/bin/env bash
# ----------------------------------------------------------------------------------------------------------------------
# Copyright (C) 2019 Ethan Pini <epini@sfu.ca>
# MIT License
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# SCT: Simple Contribution Tool
# This tool is used for repository contribution and management.
# ----------------------------------------------------------------------------------------------------------------------
exec "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.script/sct/bin/sct.sh" "$@"
