#!/usr/bin/env bash
# Copyright (C) 2019 Ethan Pini <epini@sfu.ca>
# MIT License
# ----------------------------------------------------------------------------------------------------------------------
# check: formatting
# Check the project source code formatting.
# ----------------------------------------------------------------------------------------------------------------------
fail=false

# Run:
./libexec/format-typescript.js --verify --no-vscode --no-tsconfig || fail=true

# Return:
$fail && exit 1
exit 0
